//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHuongDan
    {
        public Nullable<int> Masv { get; set; }
        public string Madt { get; set; }
        public Nullable<int> Magv { get; set; }
        public Nullable<decimal> KetQua { get; set; }
        public int Id { get; set; }
    
        public virtual TBLDeTai TBLDeTai { get; set; }
        public virtual TBLGiangVien TBLGiangVien { get; set; }
        public virtual TBLSinhVien TBLSinhVien { get; set; }
    }
}
