//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLSinhVien()
        {
            this.TBLHuongDans = new HashSet<TBLHuongDan>();
        }
    
        public int Masv { get; set; }
        public string Hotensv { get; set; }
        public string Makhoa { get; set; }
        public Nullable<int> Namsinh { get; set; }
        public string Quequan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHuongDan> TBLHuongDans { get; set; }
        public virtual TBLKhoa TBLKhoa { get; set; }
    }
}
